/**
 * JDK API Index — Hybrid Type Resolution (Compact JSON + Map)
 *
 * Architecture:
 *   1. Load compact JSON (505 KB, 3ms parse) instead of full JSON (1.6MB, 6ms)
 *   2. Build in-memory Maps on first query (~3ms)
 *   3. Hot queries: direct Map lookups (~0.01 µs)
 *   4. Inheritance: walk Map chains (~0.08 µs)
 *
 * Total cold-start: ~6ms (vs 12ms for full JSON)
 * Per query: ~0.01 µs (200x faster than pure SQLite)
 *
 * Data source: `jdk-api-index.json` (compact format)
 * Generated by `scripts/build-jdk-index.js`
 *
 * Compact JSON format:
 *   {
 *     "java.sql.Connection": {
 *       "s": "java.sql.Wrapper",        // superClass
 *       "i": ["java.lang.AutoCloseable"], // interfaces
 *       "m": {                           // methods (Object.create(null) in build)
 *         "createStatement": [
 *           ["()Ljava/sql/Statement;",   // [0] descriptor
 *            "java.sql.Statement",        // [1] returnType
 *            [],                          // [2] paramTypes
 *            ["abstract"],               // [3] modifiers
 *            ["java.sql.SQLException"],   // [4] throws
 *            0]                           // [5] deprecated (0|1)
 *         ]
 *       },
 *       "f": {                           // fields
 *         "TRANSACTION_NONE": ["int", ["static","final"]]  // [type, modifiers]
 *       }
 *     }
 *   }
 */

import * as path from 'path';
import * as fs from 'fs';

export interface VarType {
  fullClassName: string;
  packageName: string;
  className: string;
}

export interface MethodEntry {
  descriptor: string | null;
  returnType: string | null;
  paramTypes: string[];
  modifiers: string[];
  throws: string[];
  deprecated: boolean;
}

export interface FieldEntry {
  type: string | null;
  modifiers: string[];
}

interface ClassInfo {
  superClass: string | null;
  interfaces: string[];
}

// ─── In-memory index (populated on first query) ─────────────────────────

let initialized = false;

/** className → { superClass, interfaces } */
const classMap = new Map<string, ClassInfo>();

/** "className\0methodName" → MethodEntry[] (overloads) */
const methodMap = new Map<string, MethodEntry[]>();

/** "className\0fieldName" → FieldEntry */
const fieldMap = new Map<string, FieldEntry>();

// ─── Initialization ─────────────────────────────────────────────────────

function init(): void {
  if (initialized) return;
  initialized = true;

  const jsonPath = path.join(__dirname, 'jdk-api-index.json');
  if (!fs.existsSync(jsonPath)) return;

  const raw = fs.readFileSync(jsonPath, 'utf-8');
  const idx = JSON.parse(raw) as Record<string, any>;

  for (const [name, cls] of Object.entries(idx)) {
    // Class hierarchy
    classMap.set(name, {
      superClass: cls.s || null,
      interfaces: Array.isArray(cls.i) ? cls.i : [],
    });

    // Methods — compact format: mName → [[desc, retType, params, mods, throws, deprecated], ...]
    if (cls.m && typeof cls.m === 'object') {
      for (const [mName, overloads] of Object.entries(cls.m)) {
        if (!Array.isArray(overloads)) continue;
        methodMap.set(name + '\0' + mName, overloads.map((o: any[]) => ({
          descriptor: o[0] || null,
          returnType: o[1] || null,
          paramTypes: Array.isArray(o[2]) ? o[2] : [],
          modifiers: Array.isArray(o[3]) ? o[3] : [],
          throws: Array.isArray(o[4]) ? o[4] : [],
          deprecated: o[5] === 1,
        })));
      }
    }

    // Fields — compact format: fName → [type, modifiers]
    if (cls.f && typeof cls.f === 'object') {
      for (const [fName, f] of Object.entries(cls.f) as [string, any][]) {
        fieldMap.set(name + '\0' + fName, {
          type: f[0] || null,
          modifiers: Array.isArray(f[1]) ? f[1] : [],
        });
      }
    }
  }
}

// ─── Helpers ─────────────────────────────────────────────────────────────

const NON_OBJECT_TYPES = new Set([
  'void', 'boolean', 'byte', 'short', 'int', 'long', 'float', 'double', 'char',
]);

function isNonObjectType(type: string | null): boolean {
  if (!type) return true;
  if (NON_OBJECT_TYPES.has(type)) return true;
  const bare = type.replace(/\[\]$/, '');
  if (NON_OBJECT_TYPES.has(bare)) return true;
  return false;
}

function toVarType(type: string): VarType | null {
  if (isNonObjectType(type)) return null;
  if (type.includes('.')) {
    const lastDot = type.lastIndexOf('.');
    return { fullClassName: type, packageName: type.substring(0, lastDot), className: type.substring(lastDot + 1) };
  }
  return { fullClassName: type, packageName: '', className: type };
}

// ─── Public API ─────────────────────────────────────────────────────────

/**
 * Find method overloads on a class, walking the inheritance chain.
 */
function findMethods(
  className: string,
  methodName: string,
  visited: Set<string> = new Set(),
): MethodEntry[] | null {
  if (visited.has(className)) return null;
  visited.add(className);

  init();

  // Direct lookup
  const overloads = methodMap.get(className + '\0' + methodName);
  if (overloads && overloads.length > 0) {
    return overloads;
  }

  // Walk inheritance
  const cls = classMap.get(className);
  if (cls) {
    if (cls.superClass) {
      const result = findMethods(cls.superClass, methodName, visited);
      if (result) return result;
    }
    for (const iface of cls.interfaces) {
      const result = findMethods(iface, methodName, visited);
      if (result) return result;
    }
  }

  return null;
}

/**
 * Look up the return type of a method call.
 *
 * Uses inheritance resolution: if the method isn't on the class itself,
 * walks up extends/implements chain.
 */
export function lookupReturnType(
  fullClassName: string,
  methodName: string,
): VarType | null {
  const overloads = findMethods(fullClassName, methodName);
  if (!overloads || overloads.length === 0) return null;
  return toVarType(overloads[0].returnType!);
}

/**
 * Look up all overloads of a method, including inherited ones.
 */
export function lookupMethodOverloads(
  fullClassName: string,
  methodName: string,
): MethodEntry[] {
  const result = findMethods(fullClassName, methodName);
  return result || [];
}

/**
 * Look up a field's type on a class.
 */
export function lookupFieldType(
  fullClassName: string,
  fieldName: string,
): VarType | null {
  init();
  const entry = fieldMap.get(fullClassName + '\0' + fieldName);
  if (!entry || !entry.type) return null;
  return toVarType(entry.type);
}

/**
 * Get the superclass of a class.
 */
export function getSuperClass(fullClassName: string): string | null {
  init();
  const cls = classMap.get(fullClassName);
  return cls ? cls.superClass : null;
}

/**
 * Get all interfaces implemented by a class.
 */
export function getInterfaces(fullClassName: string): string[] {
  init();
  const cls = classMap.get(fullClassName);
  return cls ? cls.interfaces : [];
}

/**
 * Check if a class exists in the index.
 */
export function classExists(fullClassName: string): boolean {
  init();
  return classMap.has(fullClassName);
}

/**
 * Get statistics about the loaded index.
 */
export function getIndexStats(): { classCount: number; methodCount: number; overloadCount: number; fieldCount: number } {
  init();
  let methodCount = 0;
  let overloadCount = 0;
  for (const overloads of methodMap.values()) {
    methodCount += overloads.length;
    if (overloads.length > 1) overloadCount += overloads.length - 1;
  }
  return { classCount: classMap.size, methodCount, overloadCount, fieldCount: fieldMap.size };
}